Enhanced the design of profile
redxzeta/Awesome-Adoption pull request #203
Opened 2021-10-29 18:16 UTC by sanyogchangmai

Enhanced UI of profile. Made a responsive card to display a thumbnail and story.
![UI](https://user-images.githubusercontent.com/76730995/139483041-f27b851a-0549-4630-9434-3f9697453d24.JPG)

2021-10-29 19:31 UTC, redxzeta requested changes
just one thing to add

2021-10-29 19:31 UTC, redxzeta commented on src/components/accounts/profile/Profile.jsx
> +              <h1 className="story-title">This is title of story</h1>
can you add the date below the title

2021-10-30 04:01 UTC, sanyogchangmai commented
I have made the changes.

2021-10-30 14:27 UTC, redxzeta approved these changes

2021-10-30 14:28 UTC, merged