Paw dev
redxzeta/Awesome-Adoption pull request #236
Opened 2021-11-26 00:22 UTC by kokoaono

added tests for Pets component to render button, link and images correctly.

2021-11-26 00:33 UTC, redxzeta requested changes
Good start so far 

after making the changes, 
check out if you can test the onHover using `userEvent.hover` and `userEvent.unhover`

[hover and unhover](https://testing-library.com/docs/ecosystem-user-event#hoverelement-options)


maybe look into mocking `linkData` with 3 items or something and test it out

2021-11-26 00:33 UTC, redxzeta commented on src/components/pets/__tests__/pets.test.js
> +  expect(ClickHereButton[0]).toHaveAttribute("href", "/dog");
dont forget to check cat bird rabbit

2021-11-26 00:33 UTC, redxzeta commented on src/components/pets/__tests__/pets.test.js
> +  expect(petTypeList[0]).toHaveAttribute("href", "/dog");
dont forget to check cat bird rabbit

2021-11-26 00:34 UTC, kokoaono commented on src/components/pets/__tests__/pets.test.js
> +  expect(petTypeList[0]).toHaveAttribute("href", "/dog");
will do.

2021-11-28 19:47 UTC, redxzeta approved these changes

2021-11-28 19:47 UTC, merged