adding ability to remove favorites from favorites page
redxzeta/Awesome-Adoption pull request #335
Opened 2022-06-07 23:42 UTC by bcastillo32

I was looking to add the already existing favorites section (components/pets/Favorites/FavoriteSection.tsx) to the animal card. 

There looks to still be a bug that is affecting adding/removing from favorites that existed before I pushed this 

so I'm not sure if I did something wrong or the bug is having an impact.

2022-06-08 06:42 UTC, redxzeta requested changes
Some feedback

2022-06-08 06:42 UTC, redxzeta commented on src/components/layout/PetCard.tsx
> +          <FavoriteSection id={id} />
Home page uses this petcard  too and all the users access it. 

You can Add a button in `Favorites.tsx` where pet List map is 
```
          {petList.map((pet) => (
            <><PetCard
              key={pet.id}
              breeds={pet.breeds}
              id={pet.id}
              name={pet.name}
              photos={pet.photos}
              type={pet.type}
              primary_photo_cropped={pet.primary_photo_cropped}
            />  
// some button with remove favorites functionality
</>
          ))}
```

2022-06-08 06:42 UTC, redxzeta commented on src/components/layout/PetCard.tsx
> +          <FavoriteSection id={id} />
the remove button onlclick would have something similar to function

```
  const removeFav = async () => {
    await executeDelete((query) => query.eq("id", removalId), {
      returning: "minimal",
      count: "estimated",
    });
    dispatch(removeFavoritePet(removalId));
  };
```

2022-06-14 22:01 UTC, bcastillo32 commented on package.json
> +    "nvm": "0.0.4",
> not sure what these are for

I had to install a newer version of node and was trying a couple of different things before I got it to work. I was getting an error about needing a more recent node version so tried using nvm (node version manager)..not sure what "list" is

2022-06-14 22:17 UTC, redxzeta commented on package.json
> +    "nvm": "0.0.4",
u normally dont install `node` or `nvm` on `package.json`

you can download the latest node version here https://nodejs.org/en/ current requirements node>16

nvm you can follow instructions here https://github.com/nvm-sh/nvm#installing-and-updating tho doesn't work on windows i believe

2022-06-14 22:17 UTC, redxzeta commented on package.json
> +    "nvm": "0.0.4",
after that u can just remove these from the `package.json`

2022-06-14 23:31 UTC, bcastillo32 commented on package.json
> +    "nvm": "0.0.4",
> after that u can just remove these from the `package.json`

took care of this

2022-07-19 02:35 UTC, redxzeta approved these changes

2022-07-19 02:49 UTC, merged