made cards even
redxzeta/Awesome-Adoption pull request #362
Opened 2022-08-14 13:32 UTC by sunidhisachan

![image](https://user-images.githubusercontent.com/86006420/184539463-8fee38c2-7704-4916-a1f5-d34f0437f047.png)

2022-08-14 18:11 UTC, redxzeta requested changes
fix your pr title to `fix: card even`

![image](https://user-images.githubusercontent.com/19883954/184549516-4b745846-db55-4f70-a133-0538edec0fbc.png)

Looks too long. maybe it would be better to dl the images and crop them to all have the same width and height and then add them to the `charities.json`

2022-08-18 04:50 UTC, redxzeta commented
@sunidhisachan are u still going to work on this?

2022-08-18 14:42 UTC, sunidhisachan commented
> @sunidhisachan are u still going to work on this?

Yes , I'll do it soon

2022-08-18 20:07 UTC, sunidhisachan commented
![image](https://user-images.githubusercontent.com/86006420/185484853-44fe581c-69f7-4b80-82f1-4fc3c9c02e52.png)
  
@redxzeta  I have made the changes but unable to push them .

2022-08-22 14:38 UTC, redxzeta commented on src/App.css
> +.btn{
You could add `m-2.5` to the className

2022-08-22 14:41 UTC, redxzeta requested changes

2022-08-22 14:41 UTC, redxzeta commented on src/App.css
> +  height: 100px;
tw has some classes for height `h-24` , `h-80` 

https://tailwindcss.com/docs/height

useful tailwind vscode extension: https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss

2022-09-29 15:15 UTC, closed without merging