Added new Pet Types to `Pets.tsx`
redxzeta/Awesome-Adoption pull request #457
Opened 2022-10-06 09:24 UTC by siddhantprateek

Issue #451 
- Added Pet SVG icons to the PetIcon folder

2022-10-06 15:57 UTC, redxzeta commented on src/components/pets/Pets.tsx
> +console.log(typeData);
remove the consolelog

2022-10-06 16:32 UTC, siddhantprateek commented on src/components/pets/Pets.tsx
> +console.log(typeData);
done

2022-10-09 05:16 UTC, redxzeta commented on src/components/pets/Pets.tsx
> +
why is this here?

2022-10-09 05:17 UTC, redxzeta requested changes
add the new types in this file `src\types\PetType.ts`

2022-10-11 01:24 UTC, redxzeta commented
@siddhantprateek are you going to fix?

2023-01-02 22:43 UTC, closed without merging