Changes done
redxzeta/Awesome-Adoption pull request #66
Opened 2021-05-31 20:35 UTC by rajdama

2021-05-31 21:12 UTC, redxzeta commented
u just need to push changes to the same branch that you worked on from the previous pull request

2021-05-31 21:13 UTC, redxzeta commented
push the changes to your branch `changes`

2021-06-01 08:04 UTC, rajdama commented
> push the changes to your branch `changes`
> no need to make a new pull request

I am getting error in my git bash that Changes cannot be resolved to branch

2021-06-01 08:04 UTC, rajdama commented
so that's why I made new branch

2021-06-01 13:28 UTC, redxzeta commented
whats the error? You could also use GitHub Desktop to make it easier

2021-06-01 13:36 UTC, rajdama commented
> whats the error? You could also use GitHub Desktop to make it easier

"Changes cannot be resolved to branch this is the" error

2021-06-01 13:40 UTC, rajdama commented
I will try Github desktop

2021-06-01 13:58 UTC, rajdama commented
Now I got it what I have to do , can I make new pr in this branch i.e changes_done because a the branch Changes is not visible in git hub desktop
![Screenshot 2021-06-01 192817](https://user-images.githubusercontent.com/75741866/120335958-8a785600-c30f-11eb-9f7c-253d8b313d8b.png)

2021-06-01 14:24 UTC, redxzeta requested changes
Alright just push the changes to this branch

2021-06-01 14:24 UTC, redxzeta commented on src/components/layout/NavigationBar.js
> +
can you remove the extra spaces

2021-06-01 14:24 UTC, redxzeta commented on src/components/layout/NavigationBar.js
> +
Remove Extra spaces

2021-06-01 14:24 UTC, redxzeta commented on src/components/pets/PetType.js
> +                <Card style={{ width: "100%", paddingTop: 10 }} >
remove the inline style so it only shows `<Card>`

2021-06-01 14:53 UTC, rajdama commented
Now I am able to commit on this same branch thankyou for suggesting about GitHub Desktop :)

2021-06-01 16:06 UTC, redxzeta approved these changes

2021-06-01 16:07 UTC, merged

2021-06-01 16:07 UTC, redxzeta commented
alright looks good to go :)

2021-06-01 17:03 UTC, rajdama commented
Thankyou so much @redxzeta you really helped me a lot as I am a beginner. It was really a good experience working with you. Can I work with you in the future, if you have a team can I join ?